# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GameDesign
subtitle: ''
description: '接纳一切新鲜有趣的事物'
keywords:
author: kchris
language: zh-CN
timezone: ''
email: 1098158356@qq.com

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://cn.kongcai.tech
#permalink: :year/:month/:day/:title/
#利用hexo-abbrink插件，生成文章唯一链接
permalink: post/:abbrlink.html
abbrlink:
  alg: crc32
  rep: hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
#启用MD语法形式图片
marked:
  prependRoot: true
  postAsset: true

relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

#search
search:
  path: search/search.xml
  field: post
  content: true
# template: ./search.xml

#apalyer
aplayer:
  asset_inject: false
  meting: true

#用于生成RSS的feed插件配置
feed:
  enable: true
  type: atom
  path: link/atom.xml
  limit: 20
  hub:
  content: true
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

#douban
douban:
  id: 92678296
  builtin: true
  item_per_page: 10
  meta_max_line: 4
  #book:
  #  path: books/index.html
  # title: 'This is my book title'
  #  quote: 'This is my book quote'
  #  option:
  movie:
    path: movies/index.html
    title: '看点不一样的~'
    quote: '一些还不错的电影推荐'
    option:
  #game:
  #  path: games/index.html
  #  title: 'This is my game title'
  #  quote: 'This is my game quote'
  #  option:
  #song:
  #  path: songs/index.html
  #  title: 'This is my song title'
  #  quote: 'This is my song quote'
  #  option:
  timeout: 10000 

# steam games page
steam:
  enable: false
  steamId: '76561198326647546' #steam 64位Id
  apiKey: '1BA71B251A1422263CFB5BDB8BB4C0AA' #steam api key
  steamInfos: # 多账号配置
    - id: '76561198326647546' #steam 64位Id
      path: # 为每个帐号游戏库单独配置页面路径，默认`steamgames/{steamId}/index.html`
  freeGames: true
  path:
  title: Steam游戏库
  quote: '游戏人生'
  tab: all
  length: 1000
  imgUrl: 'https://www.steamsignature.com/profile/default/76561198326647546.png'
  proxy:
    host:
    port:
  extra_options:
    key: value

# 图表插件
# 统计图表，支持发布文章统计、发布日历、Top标签统计、分类统计、分类雷达。
# see https://www.npmjs.com/package/hexo-butterfly-charts
charts:
  enable: true # 是否启用功能
  postsChart:
    title: 文章发布统计 # 设置文章发布统计的标题，默认为空
    interval: 0 # 横坐标间隔
  tagsChart:
    title: Top 10 标签统计 # 设置标签统计的标题，默认为空
    interval: 0 # 横坐标间隔
  postsCalendar_Title: 2023年 #文章发布日历 # 设置发布日历的标题，默认为空
  categoriesChart_Title: # 设置分类统计的标题，默认为空
  categoriesRadar_Title: # 设置分类雷达的标题，默认为空


#说说插件
# Artitalk
# see https://artitalk.js.org/
#artitalk:
#  enable: true
#  appId: b85G6KOAVjmVWflXeiym5LNq-MdYXbMMI
#  appKey: Dmb0wf2uPyYIaD31nXQBYl2d
#  path:
#  js:
#  option:
#  front_matter:

# hexo-hide-posts 隐藏文章
hide_posts:
  enable: true
  # 可以改成其他你喜欢的名字
  filter: hidden
  # 指定你想要传递隐藏文章的 generator，比如让所有隐藏文章在存档页面可见
  # 常见的 generators 有：index, tag, category, archive, sitemap, feed, etc.
  public_generators: []
  # 为隐藏的文章添加 noindex meta 标签，阻止搜索引擎收录
  noindex: true

# 首页置顶轮播
# hexo-swiper-bar
# see https://zfe.space/post/hexo-swiper.html
swiper:
  enable: true
  priority: 2
  enable_page: /
  layout:
    type: id
    name: recent-posts
    index: 0
  temple_html: '<div class="recent-post-item" style="height: auto;width: 100%"><div class="blog-slider swiper-container-fade swiper-container-horizontal" id="swiper_container">${temple_html_item}</div></div>'
  plus_style: ""



# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
#  - type: git
#    repo: https://github.com/kchris1027/kchris1027.github.io.git
#    branch: master

 # - type: git
 #  repo: https://gitee.com/kchris1027/kchris1027.git
 #  branch: master

 #- type: git
 #  repo: https://e.coding.net/kchris1027/blog/kchris1027.git
 #  branch: master

  - type: git
    repo: root@45.77.97.0:/root/website_data/git/blog.git
    branch: master
